In [2]:
import pandas as pd
import numpy as np

In [3]:
songs=pd.read_csv("spotify_songs_dataset.csv")
songs.head()

,song_id,song_title,artist,album,genre,release_date,duration,popularity,stream,language,explicit_content,label,composer,producer,collaboration
0,SP0001,Space executive series.,Sydney Clark,What.,Electronic,1997-11-08,282.0,42,35055874,English,Yes,Def Jam,Amy Hatfield,Jeffrey Weaver,NaN
1,SP0002,Price last painting.,Connor Peters DDS,Nature politics.,Electronic,2015-05-10,127.0,50,9249527,English,Yes,Universal Music,Jason Gregory,Kenneth White,NaN
2,SP0003,Piece.,Anna Keith,Visit.,Pop,2024-07-08,NaN,10,76669110,English,Yes,Universal Music,Rachel Lopez,Jason Barnes,NaN
3,SP0004,Power industry your.,Zachary Simpson,Behavior evening.,Hip-Hop,2022-08-15,214.0,86,34732016,English,No,Sony Music,Thomas Li,Mrs. Becky Palmer,NaN
4,SP0005,Food animal second.,Christopher Mcgee,Front.,Pop,2023-03-05,273.0,63,96649372,English,Yes,Def Jam,Adam Wagner,Beverly Baker,NaN

In [17]:
songs['composer'].nunique()

40314

In [12]:
songs.isnull().mean()

song_id             0.00
song_title          0.00
artist              0.00
album               0.00
genre               0.00
release_date        0.00
duration            0.10
popularity          0.00
stream              0.00
language            0.05
explicit_content    0.00
label               0.00
composer            0.00
producer            0.00
collaboration       0.70
dtype: float64

In [18]:
songs=songs[['song_id','song_title','artist','album','genre','explicit_content']]

In [19]:
songs.head()

,song_id,song_title,artist,album,genre,explicit_content
0,SP0001,Space executive series.,Sydney Clark,What.,Electronic,Yes
1,SP0002,Price last painting.,Connor Peters DDS,Nature politics.,Electronic,Yes
2,SP0003,Piece.,Anna Keith,Visit.,Pop,Yes
3,SP0004,Power industry your.,Zachary Simpson,Behavior evening.,Hip-Hop,No
4,SP0005,Food animal second.,Christopher Mcgee,Front.,Pop,Yes

In [23]:
songs['artist']=songs['artist'].str.replace(" ","")
songs.head()

,song_id,song_title,artist,album,genre,explicit_content
0,SP0001,Space executive series.,SydneyClark,What.,Electronic,Yes
1,SP0002,Price last painting.,ConnorPetersDDS,Nature politics.,Electronic,Yes
2,SP0003,Piece.,AnnaKeith,Visit.,Pop,Yes
3,SP0004,Power industry your.,ZacharySimpson,Behavior evening.,Hip-Hop,No
4,SP0005,Food animal second.,ChristopherMcgee,Front.,Pop,Yes

In [76]:
songs['album']=songs['album'].str.replace(".","")
songs['song_title']=songs['song_title'].str.replace(".","")

In [133]:
songs['tags']=songs[['artist','album','genre','explicit_content']].agg(" ".join, axis=1)
songs.head(50000)

,song_id,song_title,artist,album,genre,explicit_content,tags
0,SP0001,Space executive series,SydneyClark,What,Electronic,Yes,SydneyClark What Electronic Yes
1,SP0002,Price last painting,ConnorPetersDDS,Nature politics,Electronic,Yes,ConnorPetersDDS Nature politics Electronic Yes
2,SP0003,Piece,AnnaKeith,Visit,Pop,Yes,AnnaKeith Visit Pop Yes
3,SP0004,Power industry your,ZacharySimpson,Behavior evening,Hip-Hop,No,ZacharySimpson Behavior evening Hip-Hop No
4,SP0005,Food animal second,ChristopherMcgee,Front,Pop,Yes,ChristopherMcgee Front Pop Yes
...,...,...,...,...,...,...,...
49995,SP49996,Event push do body,ShelleyRobinson,Wrong cup,Pop,No,ShelleyRobinson Wrong cup Pop No
49996,SP49997,Share clearly role,JenniferKennedy,That actually,Folk,Yes,JenniferKennedy That actually Folk Yes
49997,SP49998,Wonder type simply,HaileyWalsh,South Democrat,Pop,No,HaileyWalsh South Democrat Pop No
49998,SP49999,Company,LeahColeman,Front,Electronic,No,LeahColeman Front Electronic No
49999,SP50000,Woman plan,DanielBrown,Three,Pop,No,DanielBrown Three Pop No

In [78]:
songs['tags']=songs['tags'].apply(lambda x:x.lower())

In [79]:
songs.head()

,song_id,song_title,artist,album,genre,explicit_content,tags
0,SP0001,Space executive series,SydneyClark,What,Electronic,Yes,sydneyclark what electronic yes
1,SP0002,Price last painting,ConnorPetersDDS,Nature politics,Electronic,Yes,connorpetersdds nature politics electronic yes
2,SP0003,Piece,AnnaKeith,Visit,Pop,Yes,annakeith visit pop yes
3,SP0004,Power industry your,ZacharySimpson,Behavior evening,Hip-Hop,No,zacharysimpson behavior evening hip-hop no
4,SP0005,Food animal second,ChristopherMcgee,Front,Pop,Yes,christophermcgee front pop yes

In [109]:
songs_final=songs[['song_id','song_title','tags','artist']]
songs_final.head()

,song_id,song_title,tags,artist
0,SP0001,Space executive series,sydneyclark what electronic yes,SydneyClark
1,SP0002,Price last painting,connorpetersdds nature politics electronic yes,ConnorPetersDDS
2,SP0003,Piece,annakeith visit pop yes,AnnaKeith
3,SP0004,Power industry your,zacharysimpson behavior evening hip-hop no,ZacharySimpson
4,SP0005,Food animal second,christophermcgee front pop yes,ChristopherMcgee

In [46]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')
vectors=cv.fit_transform(songs_final['tags']).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(50000, 5000))

In [50]:
cv.get_feature_names_out()

array(['aaronalvarez', 'aaronanderson', 'aaronbailey', ...,
       'zacharysmith', 'zacharysullivan', 'zacharywilson'],
      shape=(5000,), dtype=object)

In [54]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vectors)
similarity

array([[1.        , 0.70710678, 0.40824829, ..., 0.        , 0.70710678,
        0.        ],
       [0.70710678, 1.        , 0.28867513, ..., 0.        , 0.5       ,
        0.        ],
       [0.40824829, 0.28867513, 1.        , ..., 0.33333333, 0.        ,
        0.40824829],
       ...,
       [0.        , 0.        , 0.33333333, ..., 1.        , 0.        ,
        0.40824829],
       [0.70710678, 0.5       , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.40824829, ..., 0.40824829, 0.        ,
        1.        ]], shape=(50000, 50000))

In [55]:
similarity[0]

array([1.        , 0.70710678, 0.40824829, ..., 0.        , 0.70710678,
       0.        ], shape=(50000,))

In [128]:
songs_final[(songs_final['song_title']=='Piece')]

       song_id song_title                               tags         artist
2       SP0003      Piece            annakeith visit pop yes      AnnaKeith
12399  SP12400      Piece       mr.davidnolan store folk yes  Mr.DavidNolan
14404  SP14405      Piece  lauriewoods leader electronic yes    LaurieWoods
18400  SP18401      Piece   ryanbonilla already classical no    RyanBonilla
38280  SP38281      Piece     normaclark lot produce jazz no     NormaClark

In [95]:
sorted(list(enumerate(similarity[2])),key=lambda x:x[1],reverse=True)[1:11]

[(12677, np.float64(1.0000000000000002)),
 (12901, np.float64(1.0000000000000002)),
 (32864, np.float64(1.0000000000000002)),
 (33646, np.float64(1.0000000000000002)),
 (49184, np.float64(1.0000000000000002)),
 (26337, np.float64(0.8660254037844388)),
 (4, np.float64(0.816496580927726)),
 (114, np.float64(0.816496580927726)),
 (336, np.float64(0.816496580927726)),
 (406, np.float64(0.816496580927726))]

In [123]:
def song(name):
    if len(songs_final[songs_final['song_title']==name])==1:
        song_index=songs_final[songs_final['song_title']==name].index[0]
        songs_list=sorted(list(enumerate(similarity[song_index])),key=lambda x:x[1],reverse=True)[1:11]
        for x in songs_list:
            print(songs_final.iloc[x[0]].song_title)
    elif len(songs_final[songs_final['song_title']==name])>1:
        artist=input("Enter the name of the artist")
        song_index=songs_final[(songs_final['song_title']==name) & (songs_final['artist']==artist)].index[0]
        songs_list=sorted(list(enumerate(similarity[song_index])),key=lambda x:x[1],reverse=True)[1:11]
        for x in songs_list:
            print(songs_final.iloc[x[0]].song_title)
    else:
        print("Invalid Song")

In [134]:
song('Company')

Enter the name of the artist LeahColeman

Forward understand all
Nature institution allow
Option apply speak during
News above
Them despite toward
Wish reach scene
Hospital election in
Ask answer professional
Approach mouth
Throw keep attack